name: Build LibWrt

on:
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动调整插件包，多个请用\n符号隔开。'
        required: false
        type: string
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: false
        required: false
        type: boolean

permissions: write-all

env:
  WRT_CONFIG: RE-SS-01-WIFI-NO
  WRT_THEME: argon
  WRT_NAME: OWRT
  WRT_IP: 192.168.5.1
  WRT_PW: 无

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 25.12-nss

      - name: 初始化编译环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt -yqq purge firefox
          sudo -E apt -yqq update
          sudo -E apt -yqq full-upgrade
          sudo -E apt -yqq autoremove --purge
          sudo -E apt -yqq autoclean
          sudo -E apt -yqq clean
          sudo -E apt -yqq install dos2unix libfuse-dev
          sudo bash -c 'bash <(curl -sL https://build-scripts.immortalwrt.org/init_build_environment.sh)'
          sudo -E systemctl daemon-reload
          sudo -E timedatectl set-timezone "Asia/Shanghai"

      - name: 检查脚本
        run: |
          find ./ -maxdepth 3 -type f -iregex ".*\(txt\|sh\)$" -exec dos2unix {} \; -exec chmod +x {} \;
          echo "WRT_DATE=$(TZ=UTC-8 date +"%y.%m.%d-%H.%M.%S")" >> $GITHUB_ENV

      - name: 更新 feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 自定义插件包
        run: |
          ./Scripts/Packages.sh
          ./Scripts/Handles.sh

      - name: 自定义设置
        run: |
          cat ./Config/$WRT_CONFIG.txt ./Config/GENERAL.txt >> .config
          if [ -n "${{ inputs.PACKAGE }}" ]; then
            echo -e "${{ inputs.PACKAGE }}" >> ./.config
          fi
          ./Scripts/Settings.sh
          make defconfig

      - name: 下载依赖
        if: ${{ !inputs.TEST }}
        run: |
          make download -j$(nproc)
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: 编译固件
        if: ${{ !inputs.TEST }}
        run: |
          echo -e "$(nproc) thread compile"
          make -j$(nproc) || make -j1 V=s

      - name: 整理固件
        if: ${{ !inputs.TEST }}
        run: |
          mkdir -p ./upload/
          cp -f ./.config ./upload/Config-$WRT_CONFIG-$WRT_DATE.txt
          find ./bin/targets/ -iregex ".*\(buildinfo\|json\|sha256sums\|packages\)$" -exec rm -rf {} +
          for FILE in $(find ./bin/targets/ -type f -iname "*re-ss-01*sysupgrade.bin"); do

            NEW_FILE="RE-SS-01-WIFINO-$WRT_DATE-sysupgrade.bin"
            cp -f $FILE ./upload/$NEW_FILE
          done
          find ./bin/targets/ -type f -iname "*.manifest" -exec cp -f {} ./upload/ \;

      - name: 发布 Release
        if: ${{ !inputs.TEST }}
        uses: softprops/action-gh-release@master
        with:
          tag_name: RE-SS-01-WIFINO-${{ env.WRT_DATE }}
          files: ./upload/*.*
          body: |
            京东云亚瑟 RE-SS-01 固件（WiFi-No）
            登录地址：${{ env.WRT_IP }}
            登录密码：${{ env.WRT_PW }}
            默认主题：${{ env.WRT_THEME }}
